<?php

namespace AppBundle\Repository;

/**
 * AutresTechniquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutresTechniquesRepository extends \Doctrine\ORM\EntityRepository
{
}
