<?php

namespace AppBundle\Repository;

/**
 * CollageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollageRepository extends \Doctrine\ORM\EntityRepository
{
}
