<?php

namespace AppBundle\Repository;

/**
 * createurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class createurRepository extends \Doctrine\ORM\EntityRepository
{
}
