<?php

namespace AppBundle\Repository;

/**
 * JoaillerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoaillerieRepository extends \Doctrine\ORM\EntityRepository
{
}
