<?php

namespace AppBundle\Repository;

/**
 * PeintureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeintureRepository extends \Doctrine\ORM\EntityRepository
{
}
