<?php

namespace AppBundle\Repository;

/**
 * PhotographieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotographieRepository extends \Doctrine\ORM\EntityRepository
{
}
