<?php

namespace AppBundle\Repository;

/**
 * SculptureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SculptureRepository extends \Doctrine\ORM\EntityRepository
{
}
